all:
  vars:
    control_plane_endpoint: 10.86.101.237
    load_balancer_ip_pool:
      - 10.86.101.238/31
metal:
  children:
    masters:
      hosts:
        metal0:
          {
            ansible_host: 10.86.101.221,
            mac: '00:50:56:82:87:0f',
            disk: sda,
            network_interface: ens192,
          }
        metal1:
          {
            ansible_host: 10.86.101.222,
            mac: '00:50:56:82:ee:c2',
            disk: sda,
            network_interface: ens192,
          }
        metal2:
          {
            ansible_host: 10.86.101.223,
            mac: '00:50:56:82:8b:93',
            disk: sda,
            network_interface: ens192,
          }
    workers:
      hosts: {}        
