gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host git.outletpro.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.outletpro.io
        OFFLINE_MODE: true
      repository:
        DISABLED_REPO_UNITS: repo.wiki,repo.projects,repo.packages
        DISABLE_STARS: true
        DEFAULT_BRANCH: master
      # TODO it's not reading the username from Dex correctly for now, related issues:
      # https://github.com/go-gitea/gitea/issues/25725
      # https://github.com/go-gitea/gitea/issues/24957
      # oauth2_client:
      #   ENABLE_AUTO_REGISTRATION: true
      #   USERNAME: userid
      service.explore:
        DISABLE_USERS_PAGE: true
      actions:
        ENABLED: false
      webhook:
        ALLOWED_HOST_LIST: private
postgresql-ha:
  global:
    postgresql:
      database: gitea
      password: gitea
      username: gitea
  enabled: false
  postgresql:
    repmgrPassword: changeme2
    postgresPassword: changeme1
    password: changeme4
  pgpool:
    adminPassword: changeme3
  service:
    ports:
      postgresql: 5432
  primary:
    persistence:
      size: 10Gi

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        password: gitea
        database: gitea
        username: gitea
      service:
        ports:
          postgresql: 5432
  primary:
    persistence:
      size: 10Gi      